### ISSUE TITLE
全选逻辑的问题

### ISSUE THREAD

**Issue by Utopia-Zzzz** [touchren/meituanmaicai#2]
全选的逻辑在我的设备上总是出现问题。
我简单修改了一下，没有考虑自提的情况。看看是否可行呢？
通过[这个选择器](https://github.com/touchren/meituanmaicai/blob/main/meituanmaicai.js#L353-L356)选中的radio是无法判断是否已经全选的。

代码如下：
```javascript
function check_all() {
  // 先从底部购物车右上角查看all是多少
  let allNumber = id("img_shopping_cart").findOne().parent().child(1).text();
  // 构造"结算(allNumber)"的字符串用于匹配
  let matchText = "结算(" + allNumber + ")";
  // 找到结算按钮的text
  let realText = textStartsWith("结算").findOne(200).text();
  // 如果两者不匹配，则没有全选中
  let allChecked = matchText === realText;
  if (!allChecked) {
    let radio_checkall = className("android.widget.ImageView")
      .depth(22)
      .findOne(200);
    radio_checkall.parent().click();
  }
}
```

**Comment by touchren** [comment]
是的, 我也尝试过, 没有办法判断是否 [全选] 状态
你的思路我理解是对的, 但是还要加上数量, 部分商品可能2件, 3件起购的, 这样的话又复杂了
我现在的方案比较暴力, 就是每轮第一次的时候会尝试去点击 [全选] ,  点击之后, 通过[结算]按钮判断
1. 没有任何商品选中了, 这个时候再点, 肯定就是全选了
2. 有商品选中, 那说明已经OK了

另外, 目前能抢到东西就不错了, 是不是所有商品貌似不是那么重要...

**Comment by touchren** [comment]
抱歉, 我前面理解错了, 我进APP试了下(确实已经包含了所有商品数量), 应该是可行的, 晚点我修改了试试看
多谢

**Comment by Utopia-Zzzz** [comment]
Done in commit [dbd5b43e57a5d21251ead28253a2afc5b2a324ff](https://github.com/touchren/meituanmaicai/commit/dbd5b43e57a5d21251ead28253a2afc5b2a324ff).

Close it.

Thanks a lot!
